name: Build Test

on:
  push:
    branches:
      - main

jobs:
  tsuka:
    if: ${{ startsWith(github.event.head_commit.modified, 'Tsuka/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Tsuka
    steps: 
      - name: install python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run tests
        run: |
          python -m pytest -v
  kashira:
    if: ${{ startsWith(github.event.head_commit.modified, 'Kashira/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Kashira
    steps: 
      - name: install python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run tests
        run: |
          python -m pytest -v
